### ISSUE TITLE
Replace logger with standard lib logger or an interface

### ISSUE THREAD

**Issue by owais** [a8m/kinesis-producer#10]
Projects that use kinesis-producer might use a different logging library than logrus. It would be great if kinesis-producer could expect an interface instead of a concrete type (logrus logger). It would allow us to use the same logging library in a project. Has this been discussed before? If you are open to the idea, I can try to contribute it.

Thanks

**Comment by a8m** [comment]
I like this idea, and I think this is a great practice in general when providing a third-party package. Any contribution is welcome of course 🙃
