### ISSUE TITLE
How to use logrus

### ISSUE THREAD

**Issue by konstantinj** [a8m/kinesis-producer#16]
Hi there,

I cannot get logrus to work unfortunately. I'm following the example from the readme

```
import (
	"github.com/sirupsen/logrus"
	producer "github.com/a8m/kinesis-producer"
	"github.com/a8m/kinesis-producer/loggers"
)

log := logrus.New()

&producer.Config{
  StreamName:   "test",
  BacklogCount: 2000,
  Client:       client,
  Logger:       loggers.Logrus(log),
}
```
but the package "loggers" does not exist any more only the folder. And also "Logrus" doesn't exist there anymore. It looks like readme and code drifted apart. What's the correct way here?

**Comment by a8m** [comment]
Hey @konstantinj, looks like the README docs is incorrect (link to the [package logger](https://github.com/a8m/kinesis-producer/blob/master/loggers/kplogrus/logrus.go#L9-L11)).

```go
import (
    "github.com/sirupsen/logrus"
    "github.com/a8m/kinesis-producer"
    "github.com/a8m/kinesis-producer/loggers/kplogrus"
)

func main() {
    log := logrus.New()
    cfg := &producer.Config{
        // ...
        Logger: &kplogrus.Logger{log},
    }
}
```

You are welcome to contribute and update the docs.
